---
title: "R Final Code"
author: "Marley Gonsalves"
date: "2023-12-08"
output:
  pdf_document:
    latex_engine: xelatex
    pandoc_args: "--pdf-engine-opt=--enable-write18"
fig_caption: yes
editor_options:
  chunk_output_type: console
---
```{r packages}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(lubridate)
```

```{r data cleaning}

#set R/final project as working directory

all_FC_data <- c("data/june2021.csv", "data/july2021.csv", "data/august2021.csv", "data/june2023(6.29).csv", "data/july2023(5.13.20).csv", "data/july2023(26).csv", "data/august2023(3.11.16).csv", "data/august2023(22.31).csv") #enter all flow cam data

raw_FC_data <- lapply(all_FC_data, read.csv) %>%
  bind_rows() #read files, combine into one

JEL_ABD <- raw_FC_data[, c(1, 29)] %>% #keep only name and particle diameter
  rename(Date = Name, `ParticleDiameter` = Diameter..ABD.) %>% #rename columns appropriately 
  mutate(
    Date = gsub(".*?([0-9]+)([A-Za-z]+)([0-9]+).*", "\\3 \\2 \\1", Date), #convert name of file to standard date
    Date = as.Date(Date, format = "%Y %B %d"), #Convert Date column form character to date
    Year = year(Date),# Extract the year
    Year = as.factor(Year), #convert Year to factor
    Month = month(Date, label = TRUE, abbr = FALSE) 
     ) %>%
  arrange(Date) #arrange chronologically 


#average flow cam by collection day
averaged_FC_data <- JEL_ABD %>%
  group_by(Date) %>%
  summarize(
    AvgParticleDiameter = mean(ParticleDiameter, na.rm = TRUE),
  ) 

#median particle size by collection day
median_FC_data <- JEL_ABD %>%
  group_by(Date) %>%
  summarize(
    MedParticleDiameter = median(ParticleDiameter, na.rm = TRUE),
  ) 

#count number of particles per collection day
number_FC_data <- JEL_ABD %>%
  group_by(Date) %>%
  summarize(
      Count = n()
  )

rawNERRS_data <- read.csv(file = "data/NERRS_data.csv") #load NERRS environmental data from CSV

cleanNERRS_data <- rawNERRS_data[, c(3, 7, 25)]%>% #keep only date, temperature, and Chl data
  slice(-c(1, 2))%>% #get rid of header rows
  rename(Date = X.1, Temperature = X.5, Chlorophyll = X.23) %>% #rename columns appropriately
  mutate(
    Date = as.POSIXct(strptime(Date, "%m/%d/%Y %H:%M")), #convert date to date object (with hour:minute)
    Date = as.Date(Date), #drop hour:minute
    Year = year(Date),#make a year column
    Temperature = as.numeric(Temperature), 
    Chlorophyll = as.numeric(Chlorophyll) #convert temperature and chl data to numeric
  )%>%
    group_by(Date) %>%
  summarize(
    Average_Temperature = mean(Temperature, na.rm = TRUE),
    Average_Chlorophyll = mean(Chlorophyll, na.rm = TRUE)
  ) #average temperature and chlorophyll by day



cleanNERRS_data <- rawNERRS_data[, c(3, 7, 25)] %>%
  slice(-c(1, 2)) %>%
  rename(Date = X.1, Temperature = X.5, Chlorophyll = X.23) %>%
  mutate(
    Date = as.POSIXct(strptime(Date, "%m/%d/%Y %H:%M")), # convert date to date-time object
    Date = as.Date(Date), # drop hour:minute
    Temperature = as.numeric(Temperature), 
    Chlorophyll = as.numeric(Chlorophyll) # convert temperature and chl data to numeric
  ) %>%
  group_by(Date) %>%
  summarize(
    Average_Temperature = mean(Temperature, na.rm = TRUE),
    Average_Chlorophyll = mean(Chlorophyll, na.rm = TRUE)
  ) %>%
    mutate(
      Year = year(Date),
       Month = month(Date, label = TRUE, abbr = FALSE) 
     )
#combine flow cam and NERRS data 
sampleday_data <- merge(averaged_FC_data, cleanNERRS_data, by = "Date")
sampleday_data <- merge(sampleday_data, number_FC_data, by = "Date")
sampleday_data <- merge(sampleday_data, median_FC_data, by = "Date")

sampleday_data$JulianDay <- yday(sampleday_data$Date)

sampleday_long <- sampleday_data %>%
  gather(key = "variable", value = "value", -Date)

sampleday_longts <- sampleday_data %>%
  select(-Year, -MedParticleDiameter, -JulianDay, -Month) %>%
  gather(key = "variable", value = "value", -Date) %>%
  mutate(julian_day = yday(Date))
```

```{r subset creation}
#subset flow cam data by month
JELJune <- subset(JEL_ABD, Month == "June")
JELJuly <- subset(JEL_ABD, Month == "July")
JELAugust <- subset(JEL_ABD, Month == "August")

#subset flow cam data by month and year
JELJune2021 <- JEL_ABD %>%
  filter(Date < as.Date("2021-07-01")) 
JELJuly2021 <- JEL_ABD %>%
  filter(Date > as.Date("2021-06-30") & Date < as.Date("2021-08-01"))
JELAugust2021 <- JEL_ABD %>%
  filter(Date > as.Date("2021-07-31") & Date < as.Date("2021-09-01")) 
JELJune2023 <- JEL_ABD %>%
  filter(Date > as.Date("2023-5-31") & Date < as.Date("2023-07-01"))
JELJuly2023 <- JEL_ABD %>%
  filter(Date > as.Date("2023-06-30") & Date < as.Date("2023-08-01"))
JELAugust2023 <- JEL_ABD %>%
  filter(Date > as.Date("2023-07-31") & Date < as.Date("2023-09-01"))

#subset NERRS data by year
NERRS_data_2021 <- cleanNERRS_data %>%
  filter(Date < as.Date("2021-09-01")) 
NERRS_data_2022 <- cleanNERRS_data %>%
  filter(Date > as.Date("2022-05-31") & Date < as.Date("2022-09-01"))
NERRS_data_2023 <- cleanNERRS_data %>%
  filter(Date > as.Date("2023-05-31") & Date < as.Date("2023-09-01")) 

```

```{r random useful stats}
#percentage of data points less than 100
percentage_under_threshold <- (sum(JEL_ABD$ParticleDiameter <= 100) / length(JEL_ABD$ParticleDiameter)) * 100
cat("Percentage of data points under", 100, ":", percentage_under_threshold, "%\n")

percentage_under_threshold2 <- (sum(JEL_ABD$ParticleDiameter <= 50) / length(JEL_ABD$ParticleDiameter)) * 100
cat("Percentage of data points under", 50, ":", percentage_under_threshold2, "%\n")
```

```{r graph 1, warning = FALSE,  message = FALSE, fig.cap = "\\label{fig:1} Line plots showing how chlorophyll a ($\\mu$g/L), temperature (°C), average particle diameter ($\\mu$M), and daily particle number vary over the summers of 2021 and 2023. The mean of each variable was calculated for each sampling day and compared to Julian date."}

ts_labels <- c(Average_Chlorophyll = "Chlorophyll (μg/L) ", Average_Temperature = "Temperature (°C)", AvgParticleDiameter = "Average Particle Diamter (μm)", Count = "Daily Particle Number")

ggplot(sampleday_longts, aes(x = yday(Date), y = value)) +
  geom_line(data = subset(sampleday_longts, Date > "2021-06-01" & Date < "2021-09-01"),
            aes(color = "2021")) +
  geom_line(data = subset(sampleday_longts, Date > "2023-06-01" & Date < "2023-09-01"),
            aes(color = "2023")) +
  facet_wrap(variable ~ ., scales = "free_y", 
             labeller = as_labeller(ts_labels), ncol = 2) +
  ylab(NULL)+
  labs(x = "Julian Day") +
  theme_minimal() +
  scale_color_manual(values = c("2021" = "blue", "2023" = "red"), name = "Year")+
  theme(axis.text = element_text(size = 6), axis.title = element_text(size = 8), plot.caption = element_text(size = 6))

```

```{r graph 1 stats, warning = FALSE, message = FALSE}
aov_1.1 <- aov(Average_Chlorophyll ~ Year, data = sampleday_data)
aov_1.2 <- aov(Average_Temperature ~ Year, data = sampleday_data)
aov_1.3 <- aov(AvgParticleDiameter ~ Year, data = sampleday_data)
aov_1.4 <- aov(Count ~ Year, data = sampleday_data)
aov_1.5 <- aov(Count ~ Month, data = sampleday_data)
aov_1.6 <- aov(Count ~ Month * Year, data = sampleday_data)

summary(aov_1.1)
summary(aov_1.2)
summary(aov_1.3)
summary(aov_1.4)
summary(aov_1.5)
summary(aov_1.6)


lm_1.1 <- lm(Average_Temperature ~ JulianDay, data = subset(sampleday_data, Year == 2021))
lm_1.2 <- lm(Average_Temperature ~ JulianDay, data = subset(sampleday_data, Year == 2023))
lm_1.3 <- lm(Average_Temperature ~ JulianDay, data = subset(sampleday_data, Date > "2023-06-01" & Date < "2023-08-01"))

summary(lm_1.1)
summary(lm_1.2)
summary(lm_1.3)
```

```{r graph 2, warning = FALSE, message = FALSE, fig.cap = "\\label{fig:2} Scatter plot showing the relationship between temperature (°C) and chlorophyll a concentration ($\\mu$g/L), with color differentiation between 2021 and 2023. Linear regression lines were added for all data points, and for 2021 and 2023 individually."}
ggplot(data = sampleday_data, aes(x = Average_Temperature, y = Average_Chlorophyll, color = as.factor(Year))) +
  geom_point() +
  geom_smooth(aes(color = "Overall"), method = "lm", se = FALSE) +
  geom_smooth(data = subset(sampleday_data, year(Date) == 2021), aes(color = "2021"), method = "lm", se = FALSE) +
  geom_smooth(data = subset(sampleday_data, year(Date) == 2023), aes(color = "2023"), method = "lm", se = FALSE) +
  labs(x = "Temperature (°C)", y = "Chlorophyll (μg/L)") +
  scale_color_manual(values = c("2021" = "blue", "2023" = "red", "Overall" = "black"), name = "Year") +
  theme_minimal()

ggplot(data = cleanNERRS_data, aes(x = Average_Temperature, y = Average_Chlorophyll, color = as.factor(Year))) +
  geom_point() +
  geom_smooth(aes(color = "Overall"), method = "lm", se = FALSE) +
  geom_smooth(data = subset(sampleday_data, year(Date) == 2021), aes(color = "2021"), method = "lm", se = FALSE) +
  geom_smooth(data = subset(sampleday_data, year(Date) == 2023), aes(color = "2023"), method = "lm", se = FALSE) +
  labs(x = "Temperature (°C)", y = "Chlorophyll (μM)") +
  scale_color_manual(values = c("2021" = "blue", "2023" = "red", "Overall" = "black"), name = "Year") +
  theme_minimal()
```

```{r graph 2 analysis, warning = FALSE,  message = FALSE}
lm_2.1 <- lm(Average_Chlorophyll ~ Average_Temperature, data = sampleday_data)
lm_2.2 <- lm(Average_Chlorophyll ~ Average_Temperature, data = subset(sampleday_data, Year == 2021))
lm_2.3 <- lm(Average_Chlorophyll ~ Average_Temperature, data = subset(sampleday_data, Year == 2023))

summary(lm_2.1)
summary(lm_2.2)
summary(lm_2.3)

lm_2.4 <- lm(Average_Chlorophyll ~ Average_Temperature, data = cleanNERRS_data)
lm_2.5 <- lm(Average_Chlorophyll ~ Average_Temperature, data = subset(cleanNERRS_data, Year == 2021))
lm_2.6 <- lm(Average_Chlorophyll ~ Average_Temperature, data = subset(cleanNERRS_data, Year == 2023))
summary(lm_2.4)
summary(lm_2.5)
summary(lm_2.6)

aov_5.1 <- aov(Average_Chlorophyll ~ Average_Temperature * Year, data = cleanNERRS_data)
summary(aov_5.1)
```

```{r graph 3, warning = FALSE,  message = FALSE, fig.cap = "\\label{fig:3} Particle size distribution plots of particle diameter ($\\mu$M), comparing 2021 and 2023. Months of each year are distinguished by color."}
ggplot() +
  geom_histogram(data = JELJuly2021, aes(x = ParticleDiameter, fill = "July"), binwidth = 1, color = "black", alpha = 0.7) +
  geom_histogram(data = JELJune2021, aes(x = ParticleDiameter, fill = "June"), binwidth = 1, color = "black", alpha = 0.7) +
  geom_histogram(data = JELAugust2021, aes(x = ParticleDiameter, fill = "August"), binwidth = 1, color = "black", alpha = 0.7) +
  geom_histogram(data = JELJuly2023, aes(x = ParticleDiameter, fill = "July"), binwidth = 1, color = "black", alpha = 0.7) + 
  geom_histogram(data = JELAugust2023, aes(x = ParticleDiameter, fill = "August"), binwidth = 1, color = "black", alpha = 0.7) + 
  geom_histogram(data = JELJune2023, aes(x = ParticleDiameter, fill = "June"), binwidth = 1, color = "black", alpha = 0.7) +
  labs(x = "Particle Diameter (μM)",
       y = "Frequency") +
  scale_fill_manual(
    values = c("June" = "red", "July" = "purple", "August" = "blue"),
    name = "Month")+
  theme_minimal() +
  xlim(c(0, 50)) +
  facet_wrap(Year ~ ., scales = "free", switch = "both", ncol = 2)+
  coord_cartesian(ylim = c(0, 25000))
```

```{r graph 3 analysis, warning = FALSE,  message = FALSE}
t_3.1 <- t.test(ParticleDiameter ~ Year, data = JEL_ABD)
t_3.2 <- t.test(ParticleDiameter ~ Year, data = JELJune)
t_3.3 <- t.test(ParticleDiameter ~ Year, data = JELJuly)
t_3.4 <- t.test(ParticleDiameter ~ Year, data = JELAugust)

print(t_3.1)
print(t_3.2)
print(t_3.3)
print(t_3.4)

```

```{r graph 4, warning = FALSE,  message = FALSE, fig.cap = "\\label{fig:4} Normalized particle size distribution plots of particle diameter ($\\mu$M), comparing 2021 and 2023. Months of each year are distinguished by color."}
ggplot(JEL_ABD, aes(x = ParticleDiameter, y = ..density.., fill = as.factor (Year))) +
  geom_histogram(binwidth = 1, color = "black", alpha = 0.7) +
  labs(title = "Normalized Particle Size Distribution",
       x = "Particle Size (μM)",
       y = "Density") +
  theme_minimal() +
  xlim(c(0, 50)) +
    facet_grid(Month ~ Year, scales = "free_x", space = "free_x", switch = "both") +
   scale_fill_manual(values = c("2021" = "blue", "2023" = "red"), name = "Year")+
  coord_cartesian(ylim = c (0, 0.15))

```

```{r graph 5, warning = FALSE, message = FALSE, fig.cap = "\\label{fig:5} Scatter plot showing the relationship between temperature (°C) and average particle diameter ($\\mu$M), faceted by year. A linear regression line with standard error was included for each plot."}
ggplot(sampleday_data, aes(x=Average_Temperature, y=AvgParticleDiameter)) +
  geom_point(aes(color = as.factor(Year))) +
  labs(x = "Temperature (°C)", y = "Average Particle Diameter (μM)")+
  geom_smooth(method = "lm", color = "black")+
  facet_wrap(~Year, scales = "free") +
  coord_cartesian(xlim = c(15, 24), ylim = c (14.5, 19)) +
  scale_color_manual(values = c("2021" = "blue", "2023" = "red"), name = "Year")
```

```{r graph 5 analysis, warning = FALSE,  message = FALSE}
lm_5.1 <- lm(AvgParticleDiameter ~ Average_Temperature, data = sampleday_data)
lm_5.2 <- lm(AvgParticleDiameter ~ Average_Temperature, data = subset(sampleday_data, Year == 2021))
lm_5.3 <- lm(AvgParticleDiameter ~ Average_Temperature, data = subset(sampleday_data, Year == 2023))
summary(lm_5.1)
summary(lm_5.2)
summary(lm_5.3)

lm_5.4 <- lm(Count ~ Average_Temperature, data = sampleday_data)
lm_5.5 <- lm(Count ~ Average_Temperature, data = subset(sampleday_data, Year == 2021))
lm_5.6 <- lm(Count ~ Average_Temperature, data = subset(sampleday_data, Year == 2023))
summary(lm_5.4)
summary(lm_5.5)
summary(lm_5.6)

aov_5.1 <- aov(AvgParticleDiameter ~ Average_Temperature, data = sampleday_data)
aov_5.2 <- aov(AvgParticleDiameter ~ Year * Average_Temperature, data = sampleday_data)

summary(aov_5.1)
summary(aov_5.2)

```

```{r graph 6, warning = FALSE,  message = FALSE, fig.cap = "\\label{fig:6} Scatter plot showing the relationship between average particle diameter ($\\mu$M) and chlorophyll a concentration ($\\mu$g/L). 2021 and 2023 are distinguished by color, and the number of particles on a particlar day is indicated by the size of the data point.A linear regression showing the relationship between the variables was created."}
ggplot(sampleday_data, aes(x=AvgParticleDiameter, y=Average_Chlorophyll)) +
  geom_point(aes(color = as.factor(Year), size = Count)) +
  geom_smooth(method = "lm", color = "black", se = F, fullrange = T)+
  labs(x = "Average Particle Diameter (μM)", y = "Chlorphyll (μg/L)")+
  coord_cartesian(xlim = c(14.5, 19), ylim = c (3, 15)) +
  scale_color_manual(values = c("2021" = "green2", "2023" = "green4"))+
  guides(color = guide_legend(title = "Year", size = "none")) 

```

```{r graph 6 analysis, warning = FALSE,  message = FALSE}
lm_6.1 <- lm(Average_Chlorophyll ~ AvgParticleDiameter, data = sampleday_data)
lm_6.2 <- lm(Average_Chlorophyll ~ AvgParticleDiameter, data = subset(sampleday_data, Year == 2021))
lm_6.3 <- lm(Average_Chlorophyll ~ AvgParticleDiameter, data = subset(sampleday_data, Year == 2023))
summary(lm_6.1)
summary(lm_6.2)
summary(lm_6.3)

lm_6.4 <- lm(Average_Chlorophyll ~ Count, data = sampleday_data)
lm_6.5 <- lm(Average_Chlorophyll ~ Count, data = subset(sampleday_data, Year == 2021))
lm_6.6 <- lm(Average_Chlorophyll ~ Count, data = subset(sampleday_data, Year == 2023))
summary(lm_6.4)
summary(lm_6.5)
summary(lm_6.6)
```
